# Generated by Django 5.2.15 on 2026-07-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrowrecord',
            name='uniq_active_loan_per_user_book',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='active_loan_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
